name: Master CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Update Pip Version
      run: pip install --upgrade pip==22.0.4

    - name: Verify version is not already uploaded
      run: |
        package_name="object_detection_model"
        package_version=`poetry version -s`
        count=`pip index versions --pre "${package_name}" | grep --count -F "${package_version}"`
        echo "${package_version}"
        if [ ${count} -ne 0 ]; then
            echo "version '${package_version}' for package '${package_name}' already exist in PYPI"
            exit 1
        else
            echo "Validated that version '${package_version}' for package '${package_name}' does not exist in PYPI."
            exit 0
        fi

    - name: Install Poetry
      run: pip install poetry


    - name: Linter and style check
      run: |
        pip install pre-commit==3.3.1
        pre-commit run --all-file

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true --local
        poetry install
        poetry shell

    - name: Test with pytest
      run: pytest ./tests -rA --doctest-modules --junitxml=pytest-report.xml --cov=. --cov-report=html --cov-report term-missing

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: |
          pytest-report.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - name: Build and Publish to PYPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

      run: |
        poetry config pypi-token.pypi "$(PYPI_TOKEN)"
        poetry publish --build
