name: Master CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update Pip Version
        run: pip install --upgrade pip==22.0.4

      - name: Install Pipenv
        run: pip install pipenv==2022.1.8

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev --verbose
          pipenv shell
        env:
          PIPENV_ENV_IN_PROJECT: 1

      - name: Build Package
        run: |
          pipenv run build

      - name: Publish to PYPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
